### ISSUE TITLE
depth_wise卷积适配

### ISSUE THREAD

**Issue by ChenMnZ** [LingYeAI/AdderNetCUDA#3]
作者你好，感谢开源，这是一份很棒的CUDA代码，给我提供了很大的帮助。
我注意到代码中留了`depth_wise`接口，但是cuda代码中并没有相应的适配，所以若是设置`depth_wise=true`计算结果是错误的。
请问后续有适配depth_wise加法卷积的打算吗？

**Comment by LingYeAI** [comment]
depth-wise本来是在计划中，但AdderNet的加法网络版本似乎并不是简单地将depth-wise加法化，而是把depthwise用shift来做，pointwise用adder来做，这个可以参考论文shiftaddnet，所以就没有做针对depthwise的CUDA。程序中留有这个接口是试图用已有的通用卷积来实现depthwise的卷积，但是发现相当低效，就暂时没有做。
另外，很遗憾这个版本还是一个不完善的版本，因为作者马上要毕业，这些程序暂时以能用为目标。毕业的事忙完之后我会继续完善这个项目，目前的adderCUDA至少还有五倍的速度提升潜力，如果未来有depth-wise separable conv的adder网络，我也会把这个做进去。

**Comment by Jerryme-xxm** [comment]
感谢您的工作。
我最近也在做adder相关内容，想知道您    ”程序中留有这个接口是试图用已有的通用卷积来实现depthwise的卷积，但是发现相当低效，就暂时没有做。“    中通用卷积来实现depthwise的卷积是怎么做的？
我能想到的方法就是把输入X分成channal份，然后进行channal次adder-conv，最后拼装在一起，但是感觉这样很低效。
